# SPDX-License-Identifier: CC0-1.0
---
modules-search: [ local ]

instances:
- id:       shellprocess
  module:   shellprocess
  config:   shellprocess.conf
- id:       initramfs
  module:   shellprocess
  config:   initramfs.conf
- id:       pacman
  module:   packages
  config:   packages.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - packagechooserq
    - partition
    - users
    - netinstall
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - networkcfg
    - hwclock
    - services-systemd
    - packages@pacman
    - netinstall
    - shellprocess
    - shellprocess@initramfs
    - grubcfg
    - bootloader
    - umount
  - show:
    - finished

branding: satros
prompt-at-end: true
