# SPDX-License-Identifier: CC0-1.0
---
modules-search: [ local ]

instances:
- id:       shellprocess
  module:   shellprocess
  config:   shellprocess.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - netinstall
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - networkcfg
    - hwclock
    - services-systemd
    - packages
    - netinstall
    - shellprocess
    - umount
  - show:
    - finished

branding: satros
prompt-at-end: true
